/** @externs */
/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from /private/var/tmp/_bazel_arick/c12f4ea4eaf7a974edf6cb95dd136227/execroot/angular/packages/animations/src/animation_metadata.ts:

/** @typedef {?} */
var AnimateTimings;
/**
 * @record
 * @struct
 */
function AnimationOptions() {}
 /** @type {?} */
AnimationOptions.prototype.delay;
 /** @type {?} */
AnimationOptions.prototype.params;
/**
 * @extends {AnimationOptions}
 * @record
 * @struct
 */
function AnimateChildOptions() {}
 /** @type {?} */
AnimateChildOptions.prototype.duration;
/**
 * @extends {AnimationOptions}
 * @record
 * @struct
 */
function AnimationQueryOptions() {}
 /** @type {?} */
AnimationQueryOptions.prototype.optional;
 /** @type {?} */
AnimationQueryOptions.prototype.limit;
